# Generated by Django 4.2.2 on 2023-08-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinformation',
            name='year_out',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
