# Generated by Django 4.2.2 on 2023-08-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studentinformation_year_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='year_out',
            field=models.IntegerField(blank=True),
        ),
    ]
